version: '3'

services:

    db:
        image: mysql
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports: 
            - "3306:3306"
        volumes: 
            - ./docker-data-mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        container_name: pma
        restart: always
        ports:
            - 8080:80
        depends_on: 
            - db
