version: "3"
services: 
    mongo:
        image: mongo:latest
        restart: unless-stopped
        container_name: mongodb
        ports: 
            - "27017:27017"
        volumes: 
            - ./docker-data:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
